stages:
  download:
    cmd: python src/data/download.py
    outs:
      - data/raw/GermanCredit.csv

  advanced_preprocess:
    cmd: python src/features/advanced_features.py
    deps:
      - src/features/advanced_features.py
      - data/raw/GermanCredit.csv
      - params.yaml
    outs:
      - data/processed/GermanCredit_processed.csv
      - data/processed/preprocessor.joblib

  train_advanced:
    cmd: python src/models/advanced_training.py
    deps:
      - src/models/advanced_training.py
      - data/processed/GermanCredit_processed.csv
      - params.yaml
    outs:
      - models/best_model.joblib
    metrics:
      - reports/metrics/model_comparison_*.json

  evaluate_advanced:
    cmd: python src/models/advanced_evaluation.py
    deps:
      - models/best_model.joblib
      - data/processed/GermanCredit_processed.csv
    metrics:
      - reports/metrics/evaluation_*.json
    plots:
      - reports/figures/evaluation_*.png
