train:
  test_size: 0.2
  random_state: 42
  model_type: "RandomForest"
  n_estimators: 100
  max_depth: 5

preprocessing:
  outlier_method: "iqr"
  outlier_threshold: 1.5
  scaling_method: "standard"
  imputation_strategy: "median"
  feature_selection: true
  max_features: 50

model_evaluation:
  cv_folds: 5
  scoring_metric: "roc_auc"
  threshold_optimization: true
  
hyperparameter_tuning:
  n_trials: 50
  optimization_method: "random_search"
  early_stopping: true

monitoring:
  performance_threshold: 0.85
  drift_detection: true
  alert_email: "admin@company.com"
